#
# Copyright (C) 2015 Daniel Straub, Sandro Sonntag, Christian Brandenstein, Francis Pouatcha (sso@adorsys.de, dst@adorsys.de, cbr@adorsys.de, fpo@adorsys.de)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

jboss:
    image: docker.adorsys.de/adorsys/eap-full
    ports:
        - "8080:8080"
        - "80:80"
        - "8787:8787"
        - "9990:9990"
        - "443:443"
    expose:
        - "8787"
        - "80" 
        - "8080"
        - "443"
    volumes:
        - ../oauth-http-loginmodule/target/oauth-http-loginmodule/de/adorsys/oauth/oauth-http-loginmodule:/opt/jboss/modules/system/layers/base/de/adorsys/oauth/oauth-http-loginmodule
        - ./target/oauth-server-sample.war:/opt/jboss/standalone/deployments/oauth-server-sample.war
        - ../oauth-login-theme/target/oauth-login-theme.war:/opt/jboss/standalone/deployments/oauth-login-theme.war
        - /opt/jboss/standalone/configuration
        - ./standalone.xml:/opt/jboss/standalone/configuration/standalone.xml
        - ./app-groups.properties:/opt/jboss/standalone/configuration/app-groups.properties
        - ./app-users.properties:/opt/jboss/standalone/configuration/app-users.properties
    command: bash -c "ls -la /opt/jboss/modules/system/layers/base/de/adorsys/oauth/oauth-http-loginmodule && /opt/jboss/bin/standalone.sh -Djboss.http.port=80 -Djboss.https.port=443 -b=0.0.0.0 -bmanagement=0.0.0.0 --debug"
